# Generated by Django 3.1.7 on 2021-12-02 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Scrub', max_length=40)),
                ('strength', models.IntegerField(default=7)),
                ('dexterity', models.IntegerField(default=4)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=6)),
                ('wisdom', models.IntegerField(default=9)),
                ('charisma', models.IntegerField(default=10)),
                ('gold', models.IntegerField(default=140)),
                ('silver', models.IntegerField(default=0)),
                ('copper', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
