# Generated by Django 3.1.7 on 2021-12-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=7),
        ),
    ]
