# Generated by Django 3.1.7 on 2021-12-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebox', '0002_auto_20211207_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='c_role',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=3),
        ),
    ]
