# Generated by Django 3.1.7 on 2022-01-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebox', '0003_auto_20211209_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeleeWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('damage', models.CharField(max_length=40)),
                ('weight', models.IntegerField()),
                ('cost_gp', models.IntegerField()),
            ],
        ),
    ]
