# Generated by Django 3.1.7 on 2022-01-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitebox', '0005_character_melee_weapons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='melee_weapons',
        ),
    ]
