# Generated by Django 3.1.7 on 2022-01-04 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whitebox', '0006_remove_character_melee_weapons'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeleeWeaponQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melee_weapon_quantity', to='whitebox.character')),
                ('melee_weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melee_weapon_quantity', to='whitebox.meleeweapon')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='toppings',
            field=models.ManyToManyField(related_name='melee_weapons', through='whitebox.MeleeWeaponQuantity', to='whitebox.MeleeWeapon'),
        ),
    ]
