# Generated by Django 3.1.7 on 2022-01-05 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitebox', '0007_auto_20220104_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='toppings',
            new_name='melee_weapons',
        ),
    ]
