# Generated by Django 3.1.7 on 2022-01-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitebox', '0009_auto_20220105_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rangedweaponquantity',
            old_name='melee_weapon',
            new_name='ranged_weapon',
        ),
    ]
